"""Lat, long non nullable

Revision ID: 4250772388fd
Revises: 68970f7091e1
Create Date: 2020-03-22 10:23:51.077001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4250772388fd'
down_revision = '68970f7091e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('location', 'latitude',
               existing_type=sa.FLOAT(),
               nullable=False)
    op.alter_column('location', 'longitude',
               existing_type=sa.FLOAT(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('location', 'longitude',
               existing_type=sa.FLOAT(),
               nullable=True)
    op.alter_column('location', 'latitude',
               existing_type=sa.FLOAT(),
               nullable=True)
    # ### end Alembic commands ###
