"""Lat, long non nullable

Revision ID: 4250772388fd
Revises: 68970f7091e1
Create Date: 2020-03-22 10:23:51.077001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4250772388fd'
down_revision = '68970f7091e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("location") as batch_op:
        batch_op.alter_column('latitude', nullable=False)
    with op.batch_alter_table("location") as batch_op:
        batch_op.alter_column('longitude', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("location") as batch_op:
        batch_op.alter_column('latitude', nullable=True)
    with op.batch_alter_table("location") as batch_op:
        batch_op.alter_column('longitude', nullable=True)
    # ### end Alembic commands ###
