"""CaseData - confirmed - nullable

Revision ID: 42ea5a2cde08
Revises: 58e820a979e7
Create Date: 2020-12-22 17:51:37.715243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42ea5a2cde08'
down_revision = '58e820a979e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('case_data', 'confirmed',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('case_data', 'confirmed',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
