"""Added minzdrav_name to Location

Revision ID: 58e820a979e7
Revises: 34bd3ac879b2
Create Date: 2020-03-28 21:40:39.161876

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "58e820a979e7"
down_revision = "34bd3ac879b2"
branch_labels = None
depends_on = None


LOCATIONS_DATA = [
    {
        "name": "Акмолинская область",
        "latitude": 51.86097985,
        "longitude": 69.81963567,
        "api_id": 17,
        "api_name": "Акмолинская область",
        "minzdrav_name": "Акмолинская область",
    },
    {
        "name": "Актюбинская область",
        "latitude": 48.24521185,
        "longitude": 59.45565939,
        "api_id": 14,
        "api_name": "Актюбинская область",
        "minzdrav_name": "Актюбинская область",
    },
    {
        "name": "Алматинская область",
        "latitude": 44.7706781,
        "longitude": 77.3135523,
        "api_id": 3,
        "api_name": "Алматинская область",
        "minzdrav_name": "Алматинская область",
    },
    {
        "name": "Атырауская область",
        "latitude": 47.63530685,
        "longitude": 51.66394532,
        "api_id": 4,
        "api_name": "Атырауская область",
        "minzdrav_name": "Атырауская область",
    },
    {
        "name": "Восточно-Казахстанская область",
        "latitude": 48.6224225,
        "longitude": 81.9705902,
        "api_id": 19,
        "api_name": "Восточно-Казахстанская область",
        "minzdrav_name": "Восточно-Казахстанская область",
    },
    {
        "name": "г. Алматы",
        "latitude": 43.219842549,
        "longitude": 76.918351887,
        "api_id": 1,
        "api_name": "Алматы",
        "minzdrav_name": "г. Алматы",
    },
    {
        "name": "г. Астана",
        "latitude": 51.1282205,
        "longitude": 71.4306682,
        "api_id": 2,
        "api_name": "Нур-Султан",
        "minzdrav_name": "г. Нур-Султан",
    },
    {
        "name": "г. Шымкент",
        "latitude": 42.2940787999,
        "longitude": 69.6385235157,
        "api_id": 5,
        "api_name": "Шымкент",
        "minzdrav_name": "г. Шымкент",
    },
    {
        "name": "Жамбылская область",
        "latitude": 44.16460335,
        "longitude": 72.54742413,
        "api_id": 6,
        "api_name": "Жамбылская область",
        "minzdrav_name": "Жамбылская область",
    },
    {
        "name": "Западно-Казахстанская область",
        "latitude": 49.8643499,
        "longitude": 51.5074715,
        "api_id": 20,
        "api_name": "Западно-Казахстанская область",
        "minzdrav_name": "Западно-Казахстанская область",
    },
    {
        "name": "Карагандинская область",
        "latitude": 48.6549067,
        "longitude": 70.8936445,
        "api_id": 21,
        "api_name": "Карагандинская область",
        "minzdrav_name": "Карагандинская область",
    },
    {
        "name": "Костанайская область",
        "latitude": 51.4435105,
        "longitude": 63.3924551,
        "api_id": 18,
        "api_name": "Костанайская область",
        "minzdrav_name": "Костанайская область",
    },
    {
        "name": "Кызылординская область",
        "latitude": 45.10912105,
        "longitude": 63.57213507,
        "api_id": 16,
        "api_name": "Кызылординская область",
        "minzdrav_name": "Кызылординская область",
    },
    {
        "name": "Мангистауская область",
        "latitude": 43.8568087,
        "longitude": 53.3851226,
        "api_id": 8,
        "api_name": "Мангистауская область",
        "minzdrav_name": "Мангистауская область",
    },
    {
        "name": "Павлодарская область",
        "latitude": 52.24216375,
        "longitude": 76.44494763,
        "api_id": 15,
        "api_name": "Павлодарская область",
        "minzdrav_name": "Павлодарская область",
    },
    {
        "name": "Северо-Казахстанская область",
        "latitude": 53.8356461,
        "longitude": 69.7354356,
        "api_id": 7,
        "api_name": "Северо-Казахстанская область",
        "minzdrav_name": "Северо-Казахстанская область",
    },
    {
        "name": "Туркестанская область",
        "latitude": 43.270486,
        "longitude": 67.919221,
        "api_id": 13,
        "api_name": "Туркестанская область",
        "minzdrav_name": "Туркестанская область",
    },
]


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "location", sa.Column("minzdrav_name", sa.String(length=255), nullable=True)
    )
    op.create_index(
        op.f("ix_location_minzdrav_name"), "location", ["minzdrav_name"], unique=True
    )

    locations_table = sa.sql.table(
        "location",
        sa.Column("id", sa.Integer),
        sa.Column("name", sa.String),
        sa.Column("latitude", sa.Float),
        sa.Column("longitude", sa.Float),
        sa.Column("api_id", sa.Integer),
        sa.Column("api_name", sa.String),
        sa.Column("minzdrav_name", sa.String),
    )

    op.bulk_insert(locations_table, LOCATIONS_DATA)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_location_minzdrav_name"), table_name="location")
    op.drop_column("location", "minzdrav_name")
    # ### end Alembic commands ###
