"""Added minzdrav_name to Location

Revision ID: 58e820a979e7
Revises: 34bd3ac879b2
Create Date: 2020-03-28 21:40:39.161876

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e820a979e7'
down_revision = '34bd3ac879b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('location', sa.Column('minzdrav_name', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_location_minzdrav_name'), 'location', ['minzdrav_name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_location_minzdrav_name'), table_name='location')
    op.drop_column('location', 'minzdrav_name')
    # ### end Alembic commands ###
