"""Removed Case. Added CaseData

Revision ID: 68970f7091e1
Revises: 6dedb8743b64
Create Date: 2020-03-21 15:35:42.595497

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68970f7091e1'
down_revision = '6dedb8743b64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('location_id', sa.Integer(), nullable=False),
    sa.Column('confirmed', sa.Integer(), nullable=False),
    sa.Column('recovered', sa.Integer(), nullable=True),
    sa.Column('fatal', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_case_data_date'), 'case_data', ['date'], unique=False)
    op.drop_index('ix_case_confirmed_at', table_name='case')
    op.drop_index('ix_case_created_at', table_name='case')
    op.drop_table('case')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('case',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('confirmed_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('location_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['location.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_case_created_at', 'case', ['created_at'], unique=False)
    op.create_index('ix_case_confirmed_at', 'case', ['confirmed_at'], unique=False)
    op.drop_index(op.f('ix_case_data_date'), table_name='case_data')
    op.drop_table('case_data')
    # ### end Alembic commands ###
