"""CaseData added updated_at column

Revision ID: e5d433e6f108
Revises: 4250772388fd
Create Date: 2020-03-25 01:09:15.166079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5d433e6f108'
down_revision = '4250772388fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('case_data', sa.Column('updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('case_data', 'updated_at')
    # ### end Alembic commands ###
