name: remote ssh command
on:
  push:
    paths-ignore:
      - 'tests/*'
      - '.github/*'
      - '.gitignore'
      - 'README.md'
      - 'setup.cfg'
    branches:
      - master
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: deploy via ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd /srv/covidmap
          git pull
          pipenv install --system
          flask db upgrade
          supervisorctl signal HUP server
          supervisorctl restart scheduler
