name: Pull from git repository
on:
  push:
    paths-ignore:
      - 'tests/**'
      - '.github/**'
      - .gitignore
      - README.md
      - setup.cfg
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: deploy via ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd /srv/covidmap
          git pull

name: Install new dependencies
on:
  push:
    paths:
      - Pipfile.lock
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: deploy via ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd /srv/covidmap
          pipenv install --system

name: Migrate db
on:
  push:
    paths:
      - 'migrations/**'
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: deploy via ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          cd /srv/covidmap
          flask db upgrade

name: Restart server
on:
  push:
    paths-ignore:
      - 'tests/**'
      - '.github/**'
      - .gitignore
      - README.md
      - setup.cfg
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: deploy via ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          supervisorctl signal HUP server
          supervisorctl restart scheduler
