name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Upload via rsync
    - uses: contention/action-rsync-deploy@master
    - secrets: ["DEPLOY_KEY"]
    - args: ["-avzr", "--exclude .git/ --exclude .gitignore", "root@covidmap.kz:/opt/app/"]
