name: Install new dependencies
on:
  push:
    paths:
      - Pipfile.lock
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: /srv/covidmap
    steps:
    - name: deploy via ssh
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        script: |
          pipenv install --system
